dist: trusty
sudo: true

language: node_js
node_js:
  - "10"

addons:
  chrome: stable

branches:
  only:
    - master
cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
