dist: trusty
sudo: true

language: node_js
node_js:
  - "14.4.0"

addons:
  chrome: stable

branches:
  only:
    - master
cache:
  directories:
    - ./node_modules

install:
  - npm install

before_script:
  - npm run build || true

script:
  - npm run test -watch false -browsers ChromeHeadless
